### ISSUE TITLE
Cannot get it working properly using getDocumentById()

### ISSUE THREAD

**Issue by 2ndGAB** [jweir/colorwheel#26]
Hello,

I cannot get the colorwheel working properly using `getDocumentById()`. I get errors about `cx` and `cy`.

my test is [here](http://jsfiddle.net/ndgAlainB/rm92syeq/19/)

Any idea?

**Comment by jweir** [comment]
I don't really know what you are trying to do, but the code you had seemed to be mixing up some concepts.

The `onchange` takes a function with 1 arg, the Raphael color.  

Here is an update http://jsfiddle.net/rm92syeq/29/

**Comment by 2ndGAB** [comment]
Thanks a lot, that was certainly due to incompatible versions between raphael.
I took the example from that [page](view-source:http://dmitrybaranovskiy.github.io/raphael/picker.html)
